### PR TITLE
ENG-524 Add pallet-utility

### PR DESCRIPTION
**Pull request by lreesby**

### CODE REVIEW

**Comment by antonkhvorov** [comment]
Amazing! 🚀

**Review by atomaka — CHANGES_REQUESTED** [review]
I expected a Cargo.lock change with this.

**Comment by lreesby** [comment]
> I expected a Cargo.lock change with this.

You're right.  I was making these changes through GHE while I ran benchmarks on another branch.  Will update.

**Review by justinzhou93 — APPROVED** [review]
seems like we're not really using it anywhere on the chain itself. more for users to use the batch extrinsic on it, right?

**Comment by lreesby** [comment]
> seems like we're not really using it anywhere on the chain itself. more for users to use the batch extrinsic on it, right?

It's to allow users to make batch calls to our chain.

**Pull request merged**
