### PR TITLE
Fix the issue of xtokens transferring local tokens using relative location

### PR DESCRIPTION
**Pull request by imstar15**
References:

https://github.com/AstarNetwork/Astar/blob/8846dae72e702fce8419d755516ea435f4a86b79/runtime/astar/src/xcm_config.rs#L384

```
impl orml_xtokens::Config for Runtime {
    ...
    type SelfLocation = AstarLocation;
    ...
    type ReserveProvider = AbsoluteAndRelativeReserveProvider<AstarLocationAbsolute>;
}
```

**Extrinsic call:**

https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9946#/extrinsics/decode/0x2c0103000000000700e40b540203010200f9200100e659a7a1628cdd93febc04a4e0646ea20e9f5f0ce097d9a05290d4a9e054df4e00

**Screenshoot:**

image

image

### CODE REVIEW

**Review by chrisli30 — APPROVED** [review]
Looks good to me.

**Review by Lalsha40 — APPROVED** [review]

**Comment by Isma1982** [comment]
> References:
> 
> https://github.com/AstarNetwork/Astar/blob/8846dae72e702fce8419d755516ea435f4a86b79/runtime/astar/src/xcm_config.rs#L384
> 
> ```
> impl orml_xtokens::Config for Runtime {
>     ...
>     type SelfLocation = AstarLocation;
>     ...
>     type ReserveProvider = AbsoluteAndRelativeReserveProvider<AstarLocationAbsolute>;
> }
> ```
> 
> **Extrinsic call:**
> 
> https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9946#/extrinsics/decode/0x2c0103000000000700e40b540203010200f9200100e659a7a1628cdd93febc04a4e0646ea20e9f5f0ce097d9a05290d4a9e054df4e00
> 
> **Screenshoot:**
> 
> image
> 
> 
> image
>

**Comment by chrisli30** [comment]
> **Extrinsic call:**

Hi @Isma1982, thank you for the comment. Do you have a specific ask for this PR?

**Comment by Lalsha40** [comment]
What is the pr no

**Pull request merged**
