### PR TITLE
Update weight template

### PR DESCRIPTION
**Pull request by siddharthteli12**
With ref. to #421 & #427. 

-  Weight  [template update](https://github.com/OAK-Foundation/OAK-blockchain/blob/master/.maintain/frame-weight-template.hbs) which was also causing unnecessary logs in `clippy`. 
- Also, why `weights.rs` exist but benchmarking file is missing for [automation_price](https://github.com/OAK-Foundation/OAK-blockchain/tree/master/pallets/automation-price/src)?

### CODE REVIEW

**Comment by imstar15** [comment]
> * Also, why `weights.rs` exist but benchmarking file is missing for [automation_price](https://github.com/OAK-Foundation/OAK-blockchain/tree/master/pallets/automation-price/src)?

Yes
I believe the benchmarking file is indeed missing, and we should add it.

**Comment by siddharthteli12** [comment]
For now, Just updated the weights for automation price as per the latest template. Later we can add benchmarks.
Overall, we have some consistency now. So, I believe this pr is ready for review.

**Comment by siddharthteli12** [comment]
Weight template is already updated in master. Just updated the weights in this pr. It's ready for review.

**Comment by siddharthteli12** [comment]
Will close this pr.

**Pull request closed without merging**
