### PR TITLE
Convert from substrate-based to cumulus-based parachain + add neumann

### PR DESCRIPTION
**Pull request by irsal**
- [x] Build passing (cargo +nightly build --release)
- [x] parachain running locally (producing blocks & can interact)
- [x] fix chainspec configurations
- [x] tests passing
- [ ] quadratic funding pallet passing (stretch)

### CODE REVIEW

**Comment by irsal** [comment]
Still not producing blocks. I suspect it's because of how I'm generating the genesis and wasm file

**Review by chrisli30 — APPROVED** [review]
The configuration looks good to me.

For the 2 `license = "Unlicense"`, do we need to change them to GNU 3.0 as in ()[https://github.com/OAK-Foundation/OAK-blockchain/blob/master/LICENSE]?

Reason in Jira
()[https://oak-network.atlassian.net/browse/ENG-5]

**Comment by irsal** [comment]
> Still not producing blocks. I suspect it's because of how I'm generating the genesis and wasm file

I created a separate issue/ticket to address this

**Review by chrisli30 — APPROVED** [review]
Cool, looks good to me.

**Comment by irsal** [comment]
WOOO! Officially producing blocks:

2021-12-06 13:36:24.030  INFO tokio-runtime-worker cumulus-collator: [Parachain] Starting collation. relay_parent=0x36619189e7dbcb84c6c34968d204bc39a25f944877b28c9dcddd69c38b0c0fb3 at=0x586e49052599fb0d8c80a5c9f51340c6133b8b7e43428dea8c89bc11a902f08f
2021-12-06 13:36:24.030  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent 0x586e49052599fb0d8c80a5c9f51340c6133b8b7e43428dea8c89bc11a902f08f
2021-12-06 13:36:24.032  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] 🎁 Prepared block for proposing at 7 [hash: 0xfa16a3da3a99b6b16bb59c8ffb13cb4b4eb401e2aa630fdf9d462b8c5f9a1910; parent_hash: 0x586e…f08f; extrinsics (2): [0x4be6…4375, 0xaba2…e752]]
2021-12-06 13:36:24.034  INFO tokio-runtime-worker aura: [Parachain] 🔖 Pre-sealed block for proposal at 7. Hash now 0xbfbb91e48cc216626284c76f3a89f74ab64cd11fc6308f9c42ca735fc4bfbd25, previously 0xfa16a3da3a99b6b16bb59c8ffb13cb4b4eb401e2aa630fdf9d462b8c5f9a1910.
2021-12-06 13:36:24.034  INFO tokio-runtime-worker substrate: [Parachain] ✨ Imported #7 (0xbfbb…bd25)
2021-12-06 13:36:24.035  INFO tokio-runtime-worker cumulus-collator: [Parachain] PoV size { header: 0.1787109375kb, extrinsics: 2.400390625kb, storage_proof: 2.6767578125kb }
2021-12-06 13:36:24.035  INFO tokio-runtime-worker cumulus-collator: [Parachain] Produced proof-of-validity candidate. block_hash=0xbfbb91e48cc216626284c76f3a89f74ab64cd11fc6308f9c42ca735fc4bfbd25
2021-12-06 13:36:24.494 DEBUG tokio-runtime-worker sync: [Parachain] Reannouncing block 0xbfbb91e48cc216626284c76f3a89f74ab64cd11fc6308f9c42ca735fc4bfbd25 is_best: false
2021-12-06 13:36:24.761 DEBUG tokio-runtime-worker sync: [Relaychain] Propagating transactions
2021-12-06 13:36:24.761 DEBUG tokio-runtime-worker sync: [Parachain] Propagating transactions
2021-12-06 13:36:27.663 DEBUG tokio-runtime-worker sync: [Parachain] Propagating transactions
2021-12-06 13:36:27.663 DEBUG tokio-runtime-worker sync: [Relaychain] Propagating transactions
2021-12-06 13:36:28.318  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #6 (0x586e…f08f), finalized #5 (0x07c3…fb50), ⬇ 0 ⬆ 0
2021-12-06 13:36:28.318  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (2 peers), best: #164 (0x3661…0fb3), finalized #161 (0xec89…57db), ⬇ 1.1kiB/s ⬆ 2.6kiB/s
2021-12-06 13:36:30.017 DEBUG tokio-runtime-worker sync: [Relaychain] Pre-validating received block announcement 0xc1f8d30660171554326dc36a34f7427be31029ebd84e58405d67088026b1d0de with number 165 from 12D3KooWL11A7QHrLmuXUpafXDprgsiP7a3nh8SAZ5Vvp9bqc2vy

**Pull request merged**
