### PR TITLE
Update rust version to 1.62

### PR DESCRIPTION
**Pull request by nvengal**
Some new language and cargo features that could be useful to us along with the usual slew of improvements and bug fixes.

https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1620-2022-06-30

I've been running with this locally for a few weeks and not noticed any issues.

### CODE REVIEW

**Review by rhuttman — COMMENTED** [review]
is there a CI update that needs to go along with this?

**Comment by nvengal** [comment]
> is there a CI update that needs to go along with this?

I don't think so. I think rustup just handles this for us- https://github.com/OAK-Foundation/OAK-blockchain/blob/be1a59994b94cde29832cd53facb006f0ccf78f5/.github/workflows/check.yml#L27

right, @atomaka

**Comment by atomaka** [comment]
> > is there a CI update that needs to go along with this?
> 
> I don't think so. I think rustup just handles this for us-
> 
> https://github.com/OAK-Foundation/OAK-blockchain/blob/be1a59994b94cde29832cd53facb006f0ccf78f5/.github/workflows/check.yml#L27
> 
> right, @atomaka

Correct. `rustup show` will install the appropriate rust version based on the toolchain file.

**Review by atomaka — APPROVED** [review]

**Comment by atomaka** [comment]
> [be1a599](/OAK-Foundation/OAK-blockchain/commit/be1a59994b94cde29832cd53facb006f0ccf78f5)

@rhuttman where your bela came from! Not sure why it used to say unknown.

**Review by justinzhou93 — APPROVED** [review]

**Review by rhuttman — APPROVED** [review]

**Pull request merged**
